services:
  ipfs_nod1:
    container_name: ipfs_nod1
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # Swarm port - TCP
      - "5001:5001" # API port
      - "8080:8080" # Gateway port
    volumes:
      - ./nod1:/data/ipfs
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh # Montăm scriptul în container
    entrypoint: /usr/local/bin/entrypoint.sh # Setăm scriptul ca punct de intrare

  ipfs_nod2:
    container_name: ipfs_nod2
    image: ipfs/go-ipfs:latest
    ports:
      - "4002:4001"
      - "5002:5001"
      - "8081:8080"
    volumes:
      - ./nod2:/data/ipfs
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh # Montăm același script
    entrypoint: /usr/local/bin/entrypoint.sh # Setăm scriptul ca punct de intrare
    environment:
      # Pasăm adresa de bootstrap a nodului 1 către script
      - CUSTOM_BOOTSTRAP_NODE=/dns4/ipfs_nod1/tcp/4001/p2p/12D3KooWF8Wi1iuSzu6Z2mPJgQhTBEf9Akyz9YpYi3PVL5D9JXLP
    depends_on:
      - ipfs_nod1